### ISSUE TITLE
Get all needed components

### ISSUE THREAD

**Issue by enricocirignaco** [enricocirignaco/berry_case#6]
Check which components are already available and which should be ordered.
Order needed components

**Comment by enricocirignaco** [comment]
When I get back to work I will check what is available there.
@NoFu1 could you also check it?
Here is the [BOM](https://github.com/enricocirignaco/berry_case/blob/master/docs/pcb_assembly.PDF)

**Comment by NoFu1** [comment]
@enricocirignaco we don't have any components at work, apart from some R/C etc
