### ISSUE TITLE
PCB Project

### ISSUE THREAD

**Issue by NoFu1** [enricocirignaco/berry_case#8]
1. Create (usable) Folder structure 
2. Cleanup all schematics
3. Create separate Projects for bottom/upper PCB
4. add TOP OVERLAY on C/Rs
5. Change charge controller and step - down converter to DIP
6. removing all angles < 90°
![grafik](https://user-images.githubusercontent.com/62877224/86272651-35980100-bbcf-11ea-96e7-e7a2d7793062.png)
8. make use of polygons
![grafik](https://user-images.githubusercontent.com/62877224/86272781-6a0bbd00-bbcf-11ea-8f0a-6e6ffb988239.png)

**Comment by enricocirignaco** [comment]
About point 3...what do you think about [multi board project](https://www.altium.com/documentation/altium-designer/designing-systems-with-multiple-boards-ad?version=18.1)? 
I have no experience with that but maybe it's useful.

**Comment by enricocirignaco** [comment]
About point 5...I already checked it. The TPS63031 is only available in VSON package. and the TPS61022 only in VQFN package.

**Comment by NoFu1** [comment]
I think multboard designs are a pain to use. I will use some other types(with a more practical footprint), shouldn't be a problem

**Comment by NoFu1** [comment]
@enricocirignaco tell me, when you have the PCB and know what should be changed, if u dont mind i will do the design. So you could start with the Firmware

**Comment by enricocirignaco** [comment]
Okay, we could create a issue for every bug or improovment that need to be changed. We can use the tag HW_v0.2 for this issues

**Comment by enricocirignaco** [comment]
The PCB arrived. But I don't have the components yet. I will update you
